# fly.toml file generated for home-base-enamels on 2023-03-23T22:21:37+13:00

app = "home-base-enamels"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "syd"
processes = []

[build]
  image = "aaronzhao1229/jewellery:latest" 

[env]
  ASPNETCORE_URLS="http://+:8080"
  StripeSettings__PublishableKey="pk_test_51Mnq72Am888vOmYAjcxTl0JMSjlHNBHw2Vsj7JLHCeQmrursxSOijeKbFDhUwuMRXkbyOeTBY5CnZcClPgUp6qrY00U6lfazbG"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
